#! /usr/bin/env ruby

require 'nokogiri'
require 'open-uri'

require 'dtake'

commands = ["ls","f","find","d"]

if !ARGV[0] || commands.include?(ARGV[0]) #コマンドであればそのままstart
	Dtake::CLI.start
else
	Dtake::CLI.new.d(ARGV[0]) #コマンド以外はファイル名、ダウンロード
end
